version: '3.0'

services:
  rasa:
    image: rasa/rasa:1.10.16
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    command:
    - run

  action_server:
    image: rasa/rasa-sdk:1.10.3
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"
    command:
    - run actions

networks: {rasa-network: {}}
